import type { LibraryCategory, ProjectSummary } from "@/types/library";

export const libraryCategories: LibraryCategory[] = [
  { label: "All Projects", count: 248 },
  { label: "Full Stack", count: 64 },
  { label: "Frontend", count: 48 },
  { label: "Backend", count: 36 },
  { label: "AI / ML", count: 32 },
  { label: "Mobile", count: 28 },
  { label: "Cloud / DevOps", count: 24 },
  { label: "Blockchain", count: 14 },
  { label: "Cyber Security", count: 12 },
  { label: "IoT", count: 10 },
];

export const technologyFilters = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "Python",
  "Java",
];

export const collectionFilters = [
  { label: "Build Before FAANG", count: 12 },
  { label: "Top React Projects", count: 18 },
  { label: "Top AI / ML Projects", count: 15 },
  { label: "Portfolio Essentials", count: 10 },
  { label: "Enterprise Applications", count: 8 },
  { label: "Trending This Month", count: 24 },
];

export const projects: ProjectSummary[] = [
  {
    slug: "ecommerce-platform",
    title: "E-Commerce Platform with Next.js 14, Stripe & PostgreSQL",
    shortDescription:
      "Build a production-ready store with cart management, Stripe Checkout, admin dashboard, real-time inventory, and email notifications.",
    category: "Full Stack",
    thumbnail: "/images/Image (E-Commerce Platform with Next.js 14, Stripe & PostgreSQL).png",
    isPro: true,
    tags: ["Next.js", "TypeScript", "PostgreSQL", "Stripe", "Prisma"],
    level: "Intermediate",
    rating: 4.9,
    reviewCount: 2841,
    videoCount: 86,
    duration: "42h 30m",
    learners: "12,840",
    instructor: { name: "Alex Chen", title: "Sr. Full-Stack Engineer, ex-Shopify" },
    progress: { percentComplete: 34, weeksLeft: 6 },
    status: "in-progress",
  },
  {
    slug: "realtime-chat",
    title: "Real-Time Chat App with Socket.io, Redis & React",
    shortDescription:
      "Engineer a scalable chat platform with rooms, direct messaging, file sharing, presence indicators, and full message history.",
    category: "Full Stack",
    thumbnail: "/images/Image (Real-Time Chat App with Socket.io, Redis & React).png",
    isPro: true,
    tags: ["React", "Socket.io", "Node.js", "Redis", "MongoDB"],
    level: "Advanced",
    rating: 4.8,
    reviewCount: 1920,
    videoCount: 74,
    duration: "38h 15m",
    learners: "8,400",
    instructor: { name: "Priya Sharma", title: "Principal Engineer at Twilio" },
    progress: { percentComplete: 2, weeksLeft: 5 },
    status: "in-progress",
  },
  {
    slug: "ai-resume-builder",
    title: "AI-Powered Resume Builder with OpenAI & FastAPI",
    shortDescription:
      "Create an intelligent resume generator that analyzes job descriptions, tailors content using GPT-4, and exports polished PDFs.",
    category: "AI / ML",
    thumbnail: "/images/Image (AI-Powered Resume Builder with OpenAI & FastAPI).png",
    isPro: true,
    tags: ["Python", "FastAPI", "OpenAI", "React", "PostgreSQL"],
    level: "Intermediate",
    rating: 4.9,
    reviewCount: 3102,
    videoCount: 56,
    duration: "28h 45m",
    learners: "15,200",
    instructor: { name: "Marcus Johnson", title: "ML Engineer, ex-OpenAI" },
    status: "bookmarked",
  },
  {
    slug: "netflix-clone",
    title: "Netflix Clone with React, Firebase & TMDb API",
    shortDescription:
      "Build a full streaming platform UI with authentication, movie browsing, search, trailers, and personalized watchlists.",
    category: "Frontend",
    thumbnail: "/images/Image (Netflix Clone with React, Firebase & TMDb API).png",
    isPro: true,
    tags: ["React", "Firebase", "Tailwind CSS", "TypeScript"],
    level: "Beginner",
    rating: 4.7,
    reviewCount: 4210,
    videoCount: 48,
    duration: "22h 10m",
    learners: "28,500",
    instructor: { name: "Sai Krishnan", title: "Frontend Lead, ex-Netflix" },
    status: "completed",
    completedOn: "Dec 12, 2024",
  },
  {
    slug: "microservices-architecture",
    title: "Microservices Architecture with Docker, Kubernetes & Node.js",
    shortDescription:
      "Design and deploy a microservices system with service discovery, load balancing, API gateway, and a full observability stack.",
    category: "Cloud / DevOps",
    thumbnail: "/images/Image (Microservices Architecture with Docker, Kubernetes & Node.js).png",
    isPro: true,
    tags: ["Docker", "Kubernetes", "Node.js", "gRPC", "Prometheus"],
    level: "Advanced",
    rating: 4.8,
    reviewCount: 1544,
    videoCount: 108,
    duration: "54h 20m",
    learners: "6,800",
    instructor: { name: "Elena Volkov", title: "Staff SRE, ex-Google" },
    status: "bookmarked",
  },
  {
    slug: "social-media-dashboard",
    title: "Social Media Dashboard with React, GraphQL & MongoDB",
    shortDescription:
      "Engineer a full-featured analytics dashboard with real-time updates, interactive charts, team management, and reporting.",
    category: "Full Stack",
    thumbnail: "/images/Image (Social Media Dashboard with React, GraphQL & MongoDB).png",
    isPro: true,
    tags: ["React", "GraphQL", "Apollo", "MongoDB", "Chart.js"],
    level: "Intermediate",
    rating: 4.7,
    reviewCount: 2180,
    videoCount: 68,
    duration: "34h 50m",
    learners: "9,900",
    instructor: { name: "David Kim", title: "Full-Stack Architect" },
    status: "completed",
    completedOn: "Nov 2, 2024",
  },
];

export function getProjectBySlug(slug: string) {
  return projects.find((p) => p.slug === slug);
}
